---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MasayaAoyama/kubernetes-seminar-1116.git
    targetRevision: main
    path: argorollouts/manifests/canary
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MasayaAoyama/kubernetes-seminar-1116.git
    targetRevision: main
    path: argorollouts/manifests/bluegreen
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
