apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.19.3
- role: worker
  image: kindest/node:v1.19.3
- role: worker
  image: kindest/node:v1.19.3
- role: worker
  image: kindest/node:v1.19.3
- role: worker
  image: kindest/node:v1.19.3
